name: cfs 
base: core24 
version: '0.1' 
summary: Completely Fair Scheduling snap
description: |
  Completely Fair Scheduling snap 

grade: stable 
confinement: strict 

apps:
  cfs:
    command: usr/bin/cfs
    plugs: [process-control]

parts:
  cfs:
    # See 'snapcraft plugins'
    plugin: nil
    override-pull: |
      cp $CRAFT_PROJECT_DIR/cfs.c $CRAFT_PART_SRC
    override-build: |
      gcc cfs.c -o cfs
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp cfs $CRAFT_PART_INSTALL/usr/bin
    build-packages: [build-essential]
